"""Shared dataset registry — reads from the canonical datasets.json artifact.

Single source of truth for dataset metadata (slugs, GCS paths, dimensions).
Used by the CLI and by any other consumer that needs dataset info.

The JSON is auto-generated by registry/generate.py and validated in CI.
"""

from __future__ import annotations

import json
from pathlib import Path

_REGISTRY_PATH = Path(__file__).resolve().parent.parent / "registry" / "datasets.json"

_DATASETS: dict[str, dict] | None = None


def _load() -> dict[str, dict]:
    """Lazy-load the dataset registry from JSON."""
    global _DATASETS
    if _DATASETS is not None:
        return _DATASETS
    raw = json.loads(_REGISTRY_PATH.read_text())
    _DATASETS = raw.get("datasets", {})
    return _DATASETS


def list_datasets() -> dict[str, dict]:
    """Return the full {slug → metadata} mapping."""
    return dict(_load())


def get_parquet_url(slug: str) -> str:
    """Resolve a dataset slug to its clean parquet URL on GCS."""
    datasets = _load()
    meta = datasets.get(slug)
    if meta is None:
        raise KeyError(f"Unknown dataset slug: '{slug}'")
    return meta["parquet_url"]


def get_metadata(slug: str) -> dict:
    """Return all metadata for a single dataset."""
    datasets = _load()
    meta = datasets.get(slug)
    if meta is None:
        raise KeyError(f"Unknown dataset slug: '{slug}'")
    return dict(meta)
