"""Eurostat CLI — schema-driven facts and data exploration.

Auto-discovers dataset schema from GCS parquet files and generates
facts dynamically: top regions, category breakdowns, time trends.

Usage:
    eurostat                    Auto-facts for all datasets
    eurostat gdp                Auto-facts for a specific dataset
"""

from __future__ import annotations

from contextlib import contextmanager
from dataclasses import dataclass, field
from typing import Any, Iterator

import typer
from lab_connectors.duckdb import gcs_connect
from rich.console import Console
from rich.table import Table

from ._registry import get_parquet_url, list_datasets

app = typer.Typer(help="Explore Eurostat regional data from the command line")
console = Console()

# ── Constants ─────────────────────────────────────────────────────────────────

# Non-breakdown columns (always present, entity/time/metric)
_META_COLUMNS = {"freq", "unit", "geo", "year", "value", "flag"}
# Geographic hierarchy columns — not analytical categories
_GEO_HIERARCHY = {"nuts_level", "nuts_parent_code", "nuts_parent_label_en"}

# Label/description columns (generated by clean.sql from codelists)
_LABEL_SUFFIXES = ("_label_en", "_label_it", "_desc_en", "_desc_it")

# Unit preference: more human-readable first
_UNIT_PREFERENCE = [
    "EUR_HAB", "PPS_HAB", "PPS_EU27_2020_HAB",
    "CP_MEUR", "MIO_EUR", "MIO_NAC", "MIO_PPS_EU27_2020",
    "NR", "PYP_MNAC", "CP_MNAC", "PYP_MEUR",
    "EUR_HAB_EU27_2020", "PPS_EU27_2020_HAB",
]


# ── Schema dataclass ──────────────────────────────────────────────────────────


@dataclass
class DatasetInfo:
    """Discovered schema for a Eurostat dataset on GCS."""

    slug: str
    columns: dict[str, str] = field(default_factory=dict)       # name → type
    units: list[str] = field(default_factory=list)
    years: list[int] = field(default_factory=list)
    category_cols: list[str] = field(default_factory=list)       # breakdown dims
    default_filters: dict[str, str] = field(default_factory=dict)  # cat → TOTAL-like value
    has_geo: bool = False
    is_nuts2: bool = False                                       # IT NUTS2 available
    has_italy: bool = False

    @property
    def latest_year(self) -> int | None:
        return max(self.years) if self.years else None

    @property
    def preferred_unit(self) -> str | None:
        for pref in _UNIT_PREFERENCE:
            if pref in self.units:
                return pref
        return self.units[0] if self.units else None


# ── GCS connection helpers ───────────────────────────────────────────────────


@contextmanager
def _connect(slug: str) -> Iterator[Any]:
    """Connect to a dataset's parquet on GCS with a `data` view."""
    path = get_parquet_url(slug)
    with gcs_connect(path) as con:
        con.execute(f"CREATE VIEW data AS SELECT * FROM read_parquet('{path}')")
        try:
            yield con
        except Exception:
            raise
        finally:
            try:
                con.execute("DROP VIEW IF EXISTS data")
            except Exception:
                pass  # connection may be invalidated by DuckDB fatal error


def _is_category_col(con: Any, col: str) -> bool:
    """Return True if column has between 2 and 50 distinct values (categorical dim)."""
    try:
        rows = con.sql(
            f'SELECT COUNT(DISTINCT "{col}") AS cnt FROM data '
            f'WHERE "{col}" IS NOT NULL AND "{col}" != \'\''
        ).fetchall()
        count = rows[0][0] if rows else 0
        return 2 <= count <= 50
    except Exception:
        return False


# ── Schema discovery ─────────────────────────────────────────────────────────


# Priority-ordered values to use as default filter for category columns.
# E.g. for sex: prefer 'T' (total) over 'M' or 'F'.
_DEFAULT_FILTER_VALUES = ["TOTAL", "T", "ALL", "TT_A"]

# Some category columns have known defaults regardless of data.
_KNOWN_DEFAULTS: dict[str, str] = {
    "sex": "T",
    "age": "TOTAL",
}


def _add_default_filter(con: Any, info: DatasetInfo, cat_col: str) -> None:
    """Check if a category column has a TOTAL-like default value."""
    # Known default takes precedence
    if cat_col in _KNOWN_DEFAULTS:
        info.default_filters[cat_col] = _KNOWN_DEFAULTS[cat_col]
        return

    # Scan for preferred values
    try:
        values = [
            r[0]
            for r in con.sql(
                f'SELECT DISTINCT "{cat_col}" FROM data '
                f'WHERE "{cat_col}" IS NOT NULL AND "{cat_col}" != \'\''
            ).fetchall()
        ]
    except Exception:
        return

    for preferred in _DEFAULT_FILTER_VALUES:
        if preferred in values:
            info.default_filters[cat_col] = preferred
            return


def describe(slug: str) -> DatasetInfo:
    """Discover schema and available values for a dataset."""
    info = DatasetInfo(slug=slug)

    with _connect(slug) as con:
        # 1. Column names and types
        cols = con.sql("DESCRIBE SELECT * FROM data").fetchall()
        info.columns = {c[0]: c[1] for c in cols}

        # Columns to skip when detecting categories
        label_cols = {c for c in info.columns if any(c.endswith(s) for s in _LABEL_SUFFIXES)}

        # 2. Years
        rows = con.sql("SELECT DISTINCT year FROM data WHERE year IS NOT NULL ORDER BY year").fetchall()
        info.years = [r[0] for r in rows]

        # 3. Units
        if "unit" in info.columns:
            rows = con.sql("SELECT DISTINCT unit FROM data WHERE unit IS NOT NULL").fetchall()
            info.units = [r[0] for r in rows]

        # 4. Category columns — extra dimensions beyond meta and geo-hierarchy
        all_dims = set(info.columns) - label_cols - _META_COLUMNS - _GEO_HIERARCHY
        info.category_cols = sorted(
            c for c in all_dims if _is_category_col(con, c)
        )

        # 5. Default filter values — TOTAL-like entries for each category column,
        #    plus any known defaults (like age=TOTAL) even if not a category
        info.default_filters = {}
        all_columns = set(info.columns) - label_cols - _META_COLUMNS - _GEO_HIERARCHY
        for cat_col in sorted(all_columns):
            # Only check columns that exist in data
            if _is_category_col(con, cat_col) or cat_col in _KNOWN_DEFAULTS:
                _add_default_filter(con, info, cat_col)

        # 5. Geographic info
        if "geo" in info.columns:
            info.has_geo = True
            nuts = con.sql(
                "SELECT DISTINCT nuts_level FROM data WHERE geo LIKE 'IT%' AND nuts_level IS NOT NULL"
            ).fetchall()
            info.is_nuts2 = any(r[0] == "NUTS2" for r in nuts)
            info.has_italy = len(nuts) > 0

    return info


# ── Query helpers ────────────────────────────────────────────────────────────


def _query_raw(con: Any, sql: str) -> tuple[list[str], list[list[Any]]]:
    """Run SQL, return (columns, rows)."""
    rel = con.sql(sql)
    cols = [desc[0] for desc in rel.description]
    return cols, rel.fetchall()


def _fmt(value: Any, type_hint: str = "") -> str:
    """Format a value for table display."""
    if value is None:
        return "—"
    if isinstance(value, float) or "DOUBLE" in type_hint or "FLOAT" in type_hint:
        return f"{value:,.2f}"
    if isinstance(value, int) or "BIGINT" in type_hint or "INTEGER" in type_hint:
        return f"{value:,}"
    return str(value)


def _make_table(title: str, columns: list[tuple[str, str]]) -> Table:
    """Create a Rich table."""
    t = Table(title=title, title_style="bold cyan", border_style="blue")
    for label, style in columns:
        t.add_column(label, style=style, no_wrap=True)
    return t


# ── Fact builders (schema-driven) ─────────────────────────────────────────────


def show_top_regions(con: Any, info: DatasetInfo, unit: str) -> bool:
    """Top N regions/metro-areas by value for a given unit."""
    year = info.latest_year
    if not year:
        return False

    # Apply default filters for category dimensions (e.g. sex='T', age='TOTAL')
    default_filter_clauses = [
        f'"{col}" = \'{val}\''
        for col, val in info.default_filters.items()
    ]

    # Build geo filter: prefer NUTS2 Italy, fallback to Italy, then all
    where_clauses = [f"unit = '{unit}'", "value IS NOT NULL", f"year = {year}"]
    where_clauses.extend(default_filter_clauses)
    if info.is_nuts2:
        where_clauses.append("geo LIKE 'IT%'")
        where_clauses.append("length(geo) = 4")
        where_clauses.append("nuts_level = 'NUTS2'")
    elif info.has_italy:
        where_clauses.append("geo LIKE 'IT%'")
    # else: no geo filter → all entities

    label_col = "geo_label_en" if "geo_label_en" in info.columns else "geo"
    sql = f"""
        SELECT {label_col} AS entity, year, ROUND(SUM(value)) AS val
        FROM data
        WHERE {' AND '.join(where_clauses)}
        GROUP BY entity, year
        ORDER BY val DESC
        LIMIT 10
    """

    try:
        _, rows = _query_raw(con, sql)
    except Exception as exc:
        console.print(f"  [dim]— query failed: {exc}[/]")
        return False
    if not rows:
        return False

    title = f"Top {'regions' if info.is_nuts2 else 'entities'} ({unit}, {year})"
    table = _make_table(title, [("Entity", "cyan"), ("Year", "dim"), ("Value", "green")])
    for row in rows:
        table.add_row(str(row[0]), str(row[1]), _fmt(row[2], "BIGINT"))
    console.print(table)
    return True


def show_category_breakdown(con: Any, info: DatasetInfo, unit: str) -> bool:
    """Breakdown by category dimension (nace_r2, iccs, sex, age, …)."""
    if not info.category_cols:
        return False

    year = info.latest_year
    if not year:
        return False

    shown = False
    for cat_col in info.category_cols:
        # Resolve display label column
        base = cat_col.rsplit("_", 1)[0] if "_" in cat_col else cat_col
        label_col = f"{base}_label_en"
        if label_col not in info.columns:
            label_col = cat_col

        # Apply default filters from OTHER category columns (not the one being broken down)
        breakdown_filters = [
            f'"{col}" = \'{val}\''
            for col, val in info.default_filters.items()
            if col != cat_col
        ]
        geo_filter = "geo = 'IT' AND " if info.has_italy else ""

        bf_clause = f"AND {' AND '.join(breakdown_filters)}" if breakdown_filters else ""
        sql = f"""
            SELECT {label_col} AS category, ROUND(SUM(value)) AS val
            FROM data
            WHERE {geo_filter}unit = '{unit}' AND value IS NOT NULL AND year = {year}
              AND "{cat_col}" != 'TOTAL'
              {bf_clause}
            GROUP BY category
            ORDER BY val DESC
            LIMIT 10
        """

        try:
            _, rows = _query_raw(con, sql)
        except Exception:
            continue
        if not rows:
            continue

        title = (
            f"By {cat_col.replace('_', ' ').title()} "
            f"({unit}, {'Italy' if geo_filter else 'all'}, {year})"
        )
        table = _make_table(title, [("Category", "cyan"), ("Value", "green")])
        for row in rows:
            table.add_row(str(row[0]), _fmt(row[1], "BIGINT"))
        console.print(table)
        shown = True

    return shown


def show_trend(con: Any, info: DatasetInfo, unit: str) -> bool:
    """Time series trend for a representative entity."""
    if len(info.years) < 2:
        return False

    # Apply default filters for category dimensions
    default_filter_clauses = [
        f'"{col}" = \'{val}\''
        for col, val in info.default_filters.items()
    ]

    # Pick entity
    label_col = "geo_label_en" if "geo_label_en" in info.columns else "geo"
    entity_label = "Italy" if info.has_italy else None

    if entity_label:
        entity_where = "geo = 'IT'"
    else:
        # Fall back to the entity with highest total
        try:
            _, rows = _query_raw(con, f"""
                SELECT {label_col}, SUM(value) AS total
                FROM data WHERE unit = '{unit}' AND value IS NOT NULL
                {' AND '.join(default_filter_clauses) if default_filter_clauses else ''}
                GROUP BY {label_col}
                ORDER BY total DESC LIMIT 1
            """)
            if rows:
                entity_label = str(rows[0][0])
                entity_where = f"{label_col} = '{entity_label}'"
            else:
                return False
        except Exception:
            return False

    filters = [f"unit = '{unit}'", entity_where, "value IS NOT NULL"]
    filters.extend(default_filter_clauses)
    sql = f"""
        SELECT year, ROUND(SUM(value)) AS val
        FROM data
        WHERE {' AND '.join(filters)}
        GROUP BY year
        ORDER BY year
    """

    try:
        _, rows = _query_raw(con, sql)
    except Exception:
        return False
    if not rows:
        return False

    title = f"Trend ({unit}, {entity_label})"
    table = _make_table(title, [("Year", "dim"), ("Value", "green")])
    for row in rows:
        table.add_row(str(row[0]), _fmt(row[1], "BIGINT"))
    console.print(table)
    return True


# ── Auto-facts orchestrator ────────────────────────────────────────────────────


def auto_facts(slug: str) -> bool:
    """Discover and display facts for a single dataset."""
    slug = slug.replace("-", "_")

    # Resolve short alias → full slug
    all_slugs = list_datasets()
    alias_map = {}
    for full_slug in all_slugs:
        short = full_slug.replace("eurostat_", "").replace("_nuts3", "")
        alias_map[short] = full_slug
        alias_map[full_slug] = full_slug
    slug = alias_map.get(slug, slug)

    if slug not in all_slugs:
        console.print(f"[red]Unknown dataset:[/] {slug}")
        console.print(f"Available: {', '.join(sorted(alias_map.values()))}")
        return False

    info = describe(slug)

    # Section header with summary
    year_range = f"{info.years[0]}–{info.years[-1]}" if info.years else "—"
    cats = ", ".join(info.category_cols) if info.category_cols else "—"
    title = slug.replace("_", " ").replace("nuts3", "NUTS3").title()
    console.print(f"\n[bold cyan]{title}[/]")
    console.print(
        f"  [dim]Years: {year_range}  |  Units: {len(info.units)}  |  "
        f"Categories: {cats}[/]"
    )

    # Units to display: preferred + up to 2 alternatives
    main_unit = info.preferred_unit
    alt_units = [u for u in info.units if u != main_unit and u not in ("PYP_MNAC", "CP_MNAC")]
    display_units = [main_unit] if main_unit else []
    display_units.extend(alt_units[:2])

    with _connect(slug) as con:
        for unit in display_units:
            console.print("")
            show_top_regions(con, info, unit)
            show_category_breakdown(con, info, unit)

        if main_unit:
            console.print("")
            show_trend(con, info, main_unit)

    return True


# ── CLI commands ──────────────────────────────────────────────────────────────


@app.command()
def facts(
    dataset: str = typer.Argument(
        default=None,
        help="Dataset slug (e.g. 'gdp', 'pop', 'crime', 'gva'). Omit for all.",
    ),
):
    """Show auto-discovered facts from Eurostat regional datasets."""
    if dataset:
        auto_facts(dataset)
        return

    console.print("[bold yellow]📊 Eurostat Regional Data — Facts[/]\n")
    for slug in sorted(list_datasets()):
        auto_facts(slug)


def main() -> None:
    app()


if __name__ == "__main__":
    main()
